src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="Vous possedez déjà un compte")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank
     * @Assert\Email(message = "Cette E-mail '{{ value }}' n'est pas valide.")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\Regex("/^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&-\/])[A-Za-z\d@$!%*#?&-\/]{8,}$/", message="Votre mot de passe doit contenir au moins un caractère minuscle, un caractère majuscule, un chiffre, un signe spécial de @#-_$%^&+=§ !? et entre 8 et 20 caractères")
     * @Assert\NotCompromisedPassword
     */
    private $password;

    /**
     * @ORM\Column(type="integer", length=3, nullable=true)
     */
    private $FabArmes;

    /**
     * @ORM\Column(type="integer", length=3, nullable=true)
     */
    private $FabArmures;

    /**
     * @ORM\Column(type="integer", length=3, nullable=true)
     */
    private $Ingenierie;

    /**
     * @ORM\Column(type="integer", length=3, nullable=true)
     */
    private $Joaillerie;

    /**
     * @ORM\Column(type="integer", length=3, nullable=true)
     */
    private $ArtsObscurs;

    /**
     * @ORM\Column(type="integer", length=3, nullable=true)
     */
    private $Cuisine;

    /**
     * @ORM\Column(type="integer", length=3, nullable=true)
     */
    private $Ameublement;

    /**
     * @ORM\Column(type="integer", length=2, nullable=true)
     * @Assert\Range(
     *      min = 1,
     *      max = 20,
     *      notInRangeMessage = "Votre niveau d'armes doit être entre {{ min }} et {{ max }}",)
     */
    private $SwordShield;

    /**
     * @ORM\Column(type="integer", length=2, nullable=true)
     * @Assert\Range(
     *      min = 1,
     *      max = 20,
     *      notInRangeMessage = "Votre niveau d'armes doit être entre {{ min }} et {{ max }}",)
     */
    private $Lance;

    /**
     * @ORM\Column(type="integer", length=2, nullable=true)
     * @Assert\Range(
     *      min = 1,
     *      max = 20,
     *      notInRangeMessage = "Votre niveau d'armes doit être entre {{ min }} et {{ max }}",)
     */
    private $Arc;

    /**
     * @ORM\Column(type="integer", length=2, nullable=true)
     * @Assert\Range(
     *      min = 1,
     *      max = 20,
     *      notInRangeMessage = "Votre niveau d'armes doit être entre {{ min }} et {{ max }}",)
     */
    private $BatonFeu;

    /**
     * @ORM\Column(type="integer", length=2, nullable=true)
     * @Assert\Range(
     *      min = 1,
     *      max = 20,
     *      notInRangeMessage = "Votre niveau d'armes doit être entre {{ min }} et {{ max }}",)
     */
    private $Rapiere;

    /**
     * @ORM\Column(type="integer", length=2, nullable=true)
     * @Assert\Range(
     *      min = 1,
     *      max = 20,
     *      notInRangeMessage = "Votre niveau d'armes doit être entre {{ min }} et {{ max }}",)
     */
    private $HacheDouble;

    /**
     * @ORM\Column(type="integer", length=2, nullable=true)
     * @Assert\Range(
     *      min = 1,
     *      max = 20,
     *      notInRangeMessage = "Votre niveau d'armes doit être entre {{ min }} et {{ max }}",)
     */
    private $Mousquet;

    /**
     * @ORM\Column(type="integer", length=2, nullable=true)
     * @Assert\Range(
     *      min = 1,
     *      max = 20,
     *      notInRangeMessage = "Votre niveau d'armes doit être entre {{ min }} et {{ max }}",)
     */
    private $BatonVie;

    /**
     * @ORM\Column(type="integer", length=2, nullable=true)
     * @Assert\Range(
     *      min = 1,
     *      max = 20,
     *      notInRangeMessage = "Votre niveau d'armes doit être entre {{ min }} et {{ max }}",)
     */
    private $Hachette;

    /**
     * @ORM\Column(type="integer", length=2, nullable=true)
     * @Assert\Range(
     *      min = 1,
     *      max = 20,
     *      notInRangeMessage = "Votre niveau d'armes doit être entre {{ min }} et {{ max }}",)
     */
    private $MarteauDarmes;

    /**
     * @ORM\Column(type="integer", length=2, nullable=true)
     * @Assert\Range(
     *      min = 1,
     *      max = 20,
     *      notInRangeMessage = "Votre niveau d'armes doit être entre {{ min }} et {{ max }}",)
     */
    private $GanteletsGlace;

    /**
     * @ORM\Column(type="integer", length=4, nullable=true)
     */
    private $GearScore;

    /**
     * @ORM\Column(type="integer", length=3, nullable=true)
     */
    private $StatFOR;

    /**
     * @ORM\Column(type="integer", length=3, nullable=true)
     */
    private $StatDEX;

    /**
     * @ORM\Column(type="integer", length=3, nullable=true)
     */
    private $StatINT;

    /**
     * @ORM\Column(type="integer", length=3, nullable=true)
     */
    private $StatCONCEN;

    /**
     * @ORM\Column(type="integer", length=3, nullable=true)
     */
    private $StatFORME;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $discordid;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $spe;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Votre nom de compagnie doit contenir minimum {{ limit }}",
     *      maxMessage = "Votre nom de compagnie doit contenir maximum {{ limit }}")
     */
    private $compagnie;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Choissisez Une Arme principale",
     *      maxMessage = "Merci de séléctionné une Arme principale")
     */
    private $FirstWeapon;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Choissisez Une Arme secondaire",
     *      maxMessage = "Merci de séléctionné une Arme secondaire")
     */
    private $SecondWeapon;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *      min = 1,
     *      max = 60,
     *      notInRangeMessage = "Votre niveau doit être entre {{ min }} et {{ max }}",)
     */
    private $level;

    /**
     * @ORM\Column(type="integer")
     */
    private $TailleurDePierre;

    /**
     * @ORM\Column(type="integer")
     */
    private $fonderie;

    /**
     * @ORM\Column(type="integer")
     */
    private $menuiserie;

    /**
     * @ORM\Column(type="integer")
     */
    private $tannerie;

    /**
     * @ORM\Column(type="integer")
     */
    private $tissage;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nether_gauntelet;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFabArmes(): ?string
    {
        return $this->FabArmes;
    }

    public function setFabArmes(?string $FabArmes): self
    {
        $this->FabArmes = $FabArmes;

        return $this;
    }

    public function getFabArmures(): ?string
    {
        return $this->FabArmures;
    }

    public function setFabArmures(?string $FabArmures): self
    {
        $this->FabArmures = $FabArmures;

        return $this;
    }

    public function getIngenierie(): ?string
    {
        return $this->Ingenierie;
    }

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\UserRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProfileController extends AbstractController
{
    /**
     * @Route("/profile", name="profile")
     * @IsGranted("ROLE_USER")
     */
    public function index(): Response
    {
        return $this->render('profile/index.html.twig');
    }
}

templates/profile/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}LDO - Modification de profile
{% endblock %}

{% block body %}
	<div class="container text-light">

		<h1 class="text-center m-5">
			<i class="far fa-address-card"></i>
			Modification de profile</h1>
		{{ form_start(form) }}
		<div class="row">
			<div class="col">
				{{ form_row(form.pseudo) }}
			</div>
		</div>
		<div class="row">
			<div class="col">
				{{ form_row(form.discordid) }}
			</div>
		</div>
		<div class="row">
			<div class="col">
				{{ form_row(form.GearScore) }}
			</div>
			<div class="col">
				{{ form_row(form.level) }}
			</div>
			<div class="col">
				{{ form_row(form.compagnie) }}
			</div>
		</div>
		<div class="row">
			<div class="col">
				{{ form_row(form.spe) }}
			</div>
			<div class="col">
				{{ form_row(form.FirstWeapon) }}
			</div>
			<div class="col">
				{{ form_row(form.SecondWeapon) }}
			</div>
		</div>
		<h2 class="text-center m-5"><i class="fas fa-pencil-ruler"></i> Crafting</h2>
		<div class="row">
			<div class="col">
				{{ form_row(form.FabArmes) }}
			</div>
			<div class="col">
				{{ form_row(form.FabArmures) }}
			</div>
			<div class="col">
				{{ form_row(form.Ingenierie) }}
			</div>
			<div class="col">
				{{ form_row(form.Joaillerie) }}
			</div>
		</div>
		<div class="row">
			<div class="col">
				{{ form_row(form.ArtsObscurs) }}
			</div>
			<div class="col">
				{{ form_row(form.Cuisine) }}
			</div>
			<div class="col">
				{{ form_row(form.Ameublement) }}
			</div>
			<div class="col">
				{{ form_row(form.TailleurDePierre) }}
			</div>
		</div>
		<div class="row">
			<div class="col">
				{{ form_row(form.fonderie) }}
			</div>
			<div class="col">
				{{ form_row(form.menuiserie) }}
			</div>
			<div class="col">
				{{ form_row(form.tannerie) }}
			</div>
			<div class="col">
				{{ form_row(form.tissage) }}
			</div>
		</div>
			<h2 class="text-center m-5"><i class="fas fa-box"></i> Armes</h2>
		<div class="row">

			<div class="col">
				{{ form_row(form.SwordShield) }}
			</div>
			<div class="col">
				{{ form_row(form.Lance) }}
			</div>
			<div class="col">
				{{ form_row(form.Arc) }}
			</div>
			<div class="col">
				{{ form_row(form.BatonFeu) }}
			</div>
		</div>
		<div class="row">
			<div class="col">
				{{ form_row(form.Rapiere) }}
			</div>
			<div class="col">
				{{ form_row(form.HacheDouble) }}
			</div>
			<div class="col">
				{{ form_row(form.Mousquet) }}
			</div>
			<div class="col">
				{{ form_row(form.BatonVie) }}
			</div>
		</div>
		<div class="row">
			<div class="col">
				{{ form_row(form.Hachette) }}
			</div>
			<div class="col">
				{{ form_row(form.MarteauDarmes) }}
			</div>
			<div class="col">
				{{ form_row(form.GanteletsGlace) }}
			</div>
		</div>
		<div class="row">
			<div class="col">
				{{ form_row(form.nethergauntelet) }}
			</div>
		</div>
		<div class="row">
			<div class="col text-center">
				<button type="submit" class="btn btn-primary btn-lg text-center">Enregistrer</button>
				{{ form_end(form) }}
			</div>
		</div>
	</div>
</div>{% endblock %}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}
 <div class="container">
 <h2 class="text-light text-center mt-3"><i class="fas fa-user"></i> Détails du compte : </h2>
 <a href="{{path('edit_profile')}}"><button type="button" class="btn btn-warning">Edition</button></a>
 <table class="table table-dark table-hover mt-5">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">#</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><i class="fas fa-at"></i> Email</th>
      <td>{{ app.user.email}}</td>
    </tr>
    <tr>
      <th scope="row"><i class="fas fa-user-tag"></i> Roles</th>
      <td> 
      {% for role in app.user.roles  %}
      {% if role == 'ROLE_USER' %}
            Utilisateur
      {% endif %}
      {% endfor %}
      </td>
    </tr>
    <tr>
      <th scope="row"><i class="fab fa-discord"></i> Discord</th>
      <td>{{ app.user.discordid}}</td>
    </tr>
    <tr>
      <th scope="row"><i class="fas fa-chess-king"></i> Arme Principale</th>
      <td>{{ app.user.FirstWeapon}}</td>
    </tr>
    <tr>
      <th scope="row"><i class="fas fa-chess-knight"></i> Arme Secondaire</th>
      <td>{{ app.user.SecondWeapon}}</td>
    </tr>
    <tr>
      <th scope="row"><i class="fas fa-khanda"></i> Spé</th>
      <td>{{ app.user.spe}}</td>
    </tr>
    <tr>
      <th scope="row"><i class="fas fa-child"></i> Level</th>
      <td>{{ app.user.level}}</td>
    </tr>
    <tr>
      <th scope="row"><i class="fab fa-guilded"></i> Compagnie</th>
      <td>{{ app.user.compagnie}}</td>
    </tr>
  </tbody>
</table>
</div>
<hr class="mt-3 mb-3 p-1"/>
<div class="container">
 <h2 class="text-light text-center mt-5"><i class="fas fa-balance-scale"></i> Détails des métiers : </h2>
 <table class="table table-dark table-hover mt-5">
  <thead>
    <tr>
      <th scope="col">Icon</th>
      <th scope="col">Nom</th>
      <th scope="col">Niveau</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><img src="{{ asset('assets/metier/craftweapons.png') }}" alt="Fabrication d'armes" height="72" width="72"></th>
      <td>Fabrication d'armes</td>
      <td>{{ app.user.fabarmes}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/metier/armoring.png') }}" alt="Fabrication d'armures" height="72" width="72"></th>
      <td>Fabrication d'armures</td>
      <td>{{ app.user.fabarmures}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/metier/engineering.png') }}" alt="Ingénierie" height="72" width="72"></th>
      <td>Ingénierie</td>
      <td>{{ app.user.ingenierie}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/metier/jewelcrafting.png') }}" alt="Joaillerie" height="72" width="72"></th>
      <td>Joaillerie</td>
      <td>{{ app.user.joaillerie}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/metier/arcane.png') }}" alt="Arts obscurs" height="72" width="72"></th>
      <td>Arts obscurs</td>
      <td>{{ app.user.artsobscurs}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/metier/cooking.png') }}" alt="Cuisine" height="72" width="72"></th>
      <td>Cuisine</td>
      <td>{{ app.user.cuisine}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/metier/furnishing.png') }}" alt="Ameublement" height="72" width="72"></th>
      <td>Ameublement</td>
      <td>{{ app.user.ameublement}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/metier/stonecutting.png') }}" alt="Tailleur De Pierre" height="72" width="72"></th>
      <td>Tailleur de Pierre</td>
      <td>{{ app.user.TailleurDePierre}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/metier/smelting.png') }}" alt="Fonderie" height="72" width="72"></th>
      <td>Fonderie</td>
      <td>{{ app.user.fonderie}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/metier/woodworking.png') }}" alt="Menuiserie" height="72" width="72"></th>
      <td>Menuiserie</td>
      <td>{{ app.user.menuiserie}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/metier/weaving.png') }}" alt="Tissage" height="72" width="72"></th>
      <td>Tissage</td>
      <td>{{ app.user.tissage}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/metier/leatherworking.png') }}" alt="Tannerie" height="72" width="72"></th>
      <td>Tannerie</td>
      <td>{{ app.user.tannerie}}</td>
    </tr>
  </tbody>
</table>
</div>
<hr class="mt-3 mb-3 p-1"/>
<div class="container">
 <h2 class="text-light text-center mt-5"><i class="fas fa-khanda"></i> Détails des armes : </h2>
 <table class="table table-dark table-hover mt-5">
  <thead>
    <tr>
      <th scope="col">Icon</th>
      <th scope="col">Armes</th>
      <th scope="col">Niveau</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><img src="{{ asset('assets/icon/sword.png') }}" alt="Epée & Bouclier" height="64" width="120"></th>
      <td scope="row">Epée & Bouclier</td>
      <td>{{ app.user.swordshield}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/icon/spear.png') }}" alt="Epée & Bouclier" height="64" width="120"></th>
      <td scope="row">Lance</td>
        <td>{{ app.user.lance}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/icon/bow.png') }}" alt="Epée & Bouclier" height="64" width="120"></th>
      <td scope="row">Arc</td>
      <td>{{ app.user.arc}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/icon/firestaff.png') }}" alt="Epée & Bouclier" height="64" width="120"></th>
      <td scope="row">Bâton de Feu</td>
      <td>{{ app.user.batonfeu}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/icon/rapier.png') }}" alt="Epée & Bouclier" height="64" width="120"></th>
      <td scope="row">Rapière</td>
      <td>{{ app.user.rapiere}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/icon/greataxe.png') }}" alt="Epée & Bouclier" height="64" width="120"></th>
      <td scope="row">Hache Double</td>
      <td>{{ app.user.hachedouble}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/icon/musket.png') }}" alt="Epée & Bouclier" height="64" width="120"></th>
      <td scope="row">Mousquet</td>
      <td>{{ app.user.mousquet}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/icon/lifestaff.png') }}" alt="Epée & Bouclier" height="64" width="120"></th>
      <td scope="row">Bâton de vie</td>
      <td>{{ app.user.batonvie}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/icon/hatchet.png') }}" alt="Epée & Bouclier" height="64" width="120"></th>
      <td scope="row">Hachette</td>
      <td>{{ app.user.hachette}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/icon/warhammer.png') }}" alt="Epée & Bouclier" height="64" width="120"></th>
      <td scope="row">Marteau D'armes</td>
      <td>{{ app.user.marteaudarmes}}</td>
    </tr>
    <tr>
      <th scope="row"><img src="{{ asset('assets/icon/icegauntlet.png') }}" alt="Epée & Bouclier" height="64" width="120"></th>
      <td scope="row">Gantelets de Glace</td>
      <td>{{ app.user.ganteletsglace}}</td>
    </tr>
        <tr>
      <th scope="row"><img src="{{ asset('assets/icon/voidgauntlet.png') }}" alt="Epée & Bouclier" height="64" width="120"></th>
      <td scope="row">Gantelets du Néant</td>
      <td>{{ app.user.nethergauntelet}}</td>
    </tr>
  </tbody>
</table>
</div>
<hr class="mt-3 mb-3 p-1"/>
{% endblock %}